apiVersion: v1
kind: Pod
metadata:
  name: doscont
spec:
  containers:
    - name: container1
      image: python:3.6-alpine
      command: ['sh', '-c', 'echo conteiner1 > index.html && python -m http.server 8082']
    - name: container2
      image: python:3.6-alpine
      command: ['sh', '-c', 'echo conteiner2 > index.html && python -m http.server 8083']
