version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'citizix_db'
      MYSQL_USER: 'citizix_user'
      MYSQL_PASSWORD: 'S3cret'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: